import json
from pathlib import Path

import cv2
import numpy as np

from modules.path_config import (
    PROJECT_ROOT,
    REFERENCE_DIR,
    CONFIG_DIR,
    INSPECTION_RULES_PATH,
)

IMAGE_EXTENSIONS = [".png", ".jpg", ".jpeg"]


def read_image_unicode(image_path):
    """
    한글 경로가 포함된 Windows 환경에서도 이미지를 안정적으로 읽기 위한 함수.
    cv2.imread()는 한글 경로에서 실패할 수 있어서 imdecode 방식을 사용한다.
    """
    image_data = np.fromfile(str(image_path), dtype=np.uint8)
    image = cv2.imdecode(image_data, cv2.IMREAD_COLOR)

    if image is None:
        raise FileNotFoundError(f"이미지를 읽을 수 없습니다: {image_path}")

    return image


def make_relative_path(file_path):
    """
    절대 경로를 프로젝트 기준 상대 경로로 변환한다.

    예:
    C:/Users/admin/.../Nexis_LCD_Inspection/data/reference/14-33.png

    변환 후:
    data/reference/14-33.png
    """
    return Path(file_path).relative_to(PROJECT_ROOT).as_posix()


def load_rules():
    """
    기존 inspection_rules.json이 있으면 읽고,
    없으면 새 기본 구조를 만든다.
    """
    if INSPECTION_RULES_PATH.exists():
        with open(INSPECTION_RULES_PATH, "r", encoding="utf-8") as f:
            rules_data = json.load(f)
    else:
        rules_data = {
            "version": "0.1",
            "description": "NEXIS LCD UI inspection rules generated by roi_selector.py",
            "rules": {},
        }

    if "rules" not in rules_data:
        rules_data["rules"] = {}

    return rules_data


def save_rules(rules_data):
    """
    inspection_rules.json 파일로 저장한다.
    """
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    with open(INSPECTION_RULES_PATH, "w", encoding="utf-8") as f:
        json.dump(rules_data, f, ensure_ascii=False, indent=2)

    print()
    print(f"[저장 완료] {INSPECTION_RULES_PATH}")


def get_reference_images():
    """
    data/reference 폴더 안의 이미지 파일 목록을 가져온다.
    """
    image_files = []

    for file_path in REFERENCE_DIR.iterdir():
        if file_path.is_file() and file_path.suffix.lower() in IMAGE_EXTENSIONS:
            image_files.append(file_path)

    return sorted(image_files)


def choose_reference_image(image_files):
    """
    사용자가 기준 이미지를 선택하게 한다.
    """
    print()
    print("===== 기준 이미지 목록 =====")

    for index, image_path in enumerate(image_files, start=1):
        print(f"{index}. {image_path.name}")

    print()

    while True:
        choice = input("ROI를 지정할 기준 이미지 번호를 입력하세요: ").strip()

        if choice.isdigit():
            choice_number = int(choice)

            if 1 <= choice_number <= len(image_files):
                return image_files[choice_number - 1]

        print("잘못 입력했습니다. 목록에 있는 번호를 다시 입력하세요.")


def input_with_default(message, default_value):
    """
    사용자가 Enter만 누르면 기본값을 사용한다.
    """
    user_input = input(f"{message} [기본값: {default_value}]: ").strip()

    if user_input == "":
        return default_value

    return user_input


def select_roi_with_mouse(image, window_name):
    """
    OpenCV 창에서 마우스로 ROI를 선택한다.

    사용법:
    - 마우스로 검사할 영역 드래그
    - Enter 또는 Space 키로 확정
    - C 키를 누르면 취소
    """
    bbox = cv2.selectROI(window_name, image, showCrosshair=True, fromCenter=False)

    cv2.destroyWindow(window_name)

    x, y, w, h = bbox

    return [int(x), int(y), int(w), int(h)]


def create_roi_rule(image):
    """
    ROI 하나를 마우스로 선택하고,
    해당 ROI의 검사 정보를 입력받아 dict로 만든다.
    """
    print()
    print("===== 새 ROI 등록 =====")

    roi_id = input("ROI ID를 입력하세요. 예: guide_image_area: ").strip()
    label = input("ROI 설명을 입력하세요. 예: 왼쪽 안내 그림 영역: ").strip()

    check_type = input_with_default("검사 방식을 입력하세요. 현재는 ssim 사용", "ssim")

    importance = input_with_default(
        "중요도를 입력하세요. critical / warning / minor", "critical"
    )

    ssim_pass = float(input_with_default("PASS 기준 SSIM 값을 입력하세요", "0.90"))

    ssim_review = float(input_with_default("REVIEW 기준 SSIM 값을 입력하세요", "0.75"))

    print()
    print("OpenCV 창이 뜨면 마우스로 검사할 영역을 드래그하세요.")
    print("영역 선택 후 Enter 또는 Space를 누르면 확정됩니다.")
    print("잘못 선택했다면 C 키를 누르면 취소됩니다.")

    window_name = "ROI Selector"
    bbox = select_roi_with_mouse(image, window_name)

    if bbox[2] == 0 or bbox[3] == 0:
        print("[취소됨] ROI 선택이 취소되었거나 영역 크기가 0입니다.")
        return None

    expected_issue = input_with_default(
        "예상 오류 설명을 입력하세요", "기준 이미지와 비교 이미지의 ROI 차이 확인"
    )

    roi_rule = {
        "roi_id": roi_id,
        "label": label,
        "check_type": check_type,
        "bbox": bbox,
        "ssim_pass": ssim_pass,
        "ssim_review": ssim_review,
        "importance": importance,
        "expected_issue": expected_issue,
    }

    print()
    print("[ROI 등록 완료]")
    print(json.dumps(roi_rule, ensure_ascii=False, indent=2))

    return roi_rule


def register_rois_for_image(reference_image_path):
    """
    선택한 기준 이미지에 대해 여러 개의 ROI를 등록한다.
    """
    image = read_image_unicode(reference_image_path)
    height, width = image.shape[:2]

    screen_id = reference_image_path.stem

    print()
    print("===== 화면 정보 입력 =====")
    print(f"선택한 기준 이미지: {reference_image_path.name}")
    print(f"자동 screen_id: {screen_id}")
    print(f"이미지 크기: width={width}, height={height}")

    screen_type = input_with_default(
        "화면 유형을 입력하세요. 예: course_card_type, guide_type", "manual_sample"
    )

    expected_final_result = input_with_default(
        "이 샘플의 예상 최종 결과를 입력하세요. PASS / FAIL / REVIEW", "FAIL"
    )

    description = input_with_default(
        "화면 설명을 입력하세요", "OpenCV ROI selector로 등록한 검사 기준"
    )

    rules_data = load_rules()

    existing_rule = rules_data["rules"].get(screen_id)

    if existing_rule is not None:
        print()
        print(f"[주의] 이미 {screen_id}에 대한 규칙이 있습니다.")
        print(f"현재 등록된 ROI 개수: {len(existing_rule.get('rois', []))}")

        reset_choice = input("기존 ROI를 지우고 새로 등록할까요? y/n: ").strip().lower()

        if reset_choice == "y":
            rois = []
        else:
            rois = existing_rule.get("rois", [])
    else:
        rois = []

    while True:
        roi_rule = create_roi_rule(image)

        if roi_rule is not None:
            rois.append(roi_rule)

        continue_choice = input("ROI를 더 추가할까요? y/n: ").strip().lower()

        if continue_choice != "y":
            break

    rules_data["rules"][screen_id] = {
        "screen_id": screen_id,
        "sample_name": reference_image_path.name,
        "screen_type": screen_type,
        "reference_image": make_relative_path(reference_image_path),
        "image_size": {"width": width, "height": height},
        "expected_final_result": expected_final_result,
        "description": description,
        "rois": rois,
    }

    save_rules(rules_data)

    print()
    print("===== 등록 결과 요약 =====")
    print(f"screen_id: {screen_id}")
    print(f"등록된 ROI 개수: {len(rois)}")


def main():
    image_files = get_reference_images()

    if not image_files:
        print(f"[오류] 기준 이미지가 없습니다: {REFERENCE_DIR}")
        print("data/reference 폴더에 14-33.png, 15-65.png를 넣었는지 확인하세요.")
        return

    selected_image = choose_reference_image(image_files)
    register_rois_for_image(selected_image)


if __name__ == "__main__":
    main()
